$(document).ready(function(){
    $('.slider-1').slick(
        {
            autoplay:true,
            autoplaySpeed:1000,
            arrow:false
        }
    );
  });
  $(document).ready(function(){
    $('.slider-2').slick(        
    {
        autoplay:true,
        autoplaySpeed:1500,
        arrow:false
    });
  });
  $(document).ready(function(){
    $('.slider-3').slick(
        {
            autoplay:true,
            autoplaySpeed:1800,
            arrow:false
        }
    );
  });
  $(document).ready(function(){
    $('.slider-4').slick(
        {
            autoplay:true,
            autoplaySpeed:2000,
            arrow:false
        }
    );
  });
  $(document).ready(function(){
    $('.slider-5').slick(
        {
            autoplay:true,
            autoplaySpeed:1000
        }
    );
  });
  $(document).ready(function(){
    $('.slider-6').slick(
        {
            autoplay:true,
            autoplaySpeed:1100
        }
    );
  });